version: '3.8'

services:
  acas-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acas-backend
    ports:
      - "${SERVER_PORT:-3001}:3001"
    environment:
      # Server Configuration
      - SERVER_PORT=${SERVER_PORT:-3001}
      - SERVER_SERVLET_CONTEXT_PATH=/api
      
      # Database Configuration
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DATABASE_DRIVER:-org.h2.Driver}
      
      # JPA Configuration
      - SPRING_JPA_DATABASE_PLATFORM=${DATABASE_PLATFORM:-org.hibernate.dialect.H2Dialect}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_DDL_AUTO:-update}
      - SPRING_JPA_SHOW_SQL=${JPA_SHOW_SQL:-false}
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-604800000}
      
      # CORS Configuration
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
      
      # Logging
      - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL:-INFO}
      - LOGGING_LEVEL_COM_ACAS=${APP_LOGGING_LEVEL:-DEBUG}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - acas-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  acas-network:
    driver: bridge
